spring.application.name=novapos-api
server.port=8080
server.servlet.context-path=/

spring.datasource.url=jdbc:h2:mem:novapos;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.data.redis.repositories.enabled=false

novapos.security.jwt-secret=novapos-local-dev-secret-change-me
novapos.security.access-token-minutes=90
novapos.security.refresh-token-minutes=1440
