create table if not exists tenant (
    id varchar(64) primary key,
    code varchar(64) not null unique,
    name varchar(255) not null,
    created_at timestamp not null
);

create table if not exists branch (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    name varchar(255) not null,
    code varchar(64) not null,
    timezone varchar(64) not null,
    created_at timestamp not null
);

create table if not exists device (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    branch_id varchar(64) not null,
    device_code varchar(64) not null,
    device_type varchar(64) not null,
    last_sync_at timestamp
);

create table if not exists event_store (
    id bigint generated by default as identity primary key,
    event_uuid varchar(64) not null,
    tenant_id varchar(64) not null,
    branch_id varchar(64) not null,
    device_id varchar(64) not null,
    aggregate_type varchar(64) not null,
    aggregate_id varchar(64) not null,
    event_type varchar(128) not null,
    device_sequence bigint not null,
    aggregate_version bigint not null,
    schema_version integer not null,
    status varchar(32) not null,
    payload_json clob not null,
    occurred_at timestamp not null,
    received_at timestamp not null
);

create unique index if not exists idx_event_store_uuid
    on event_store (tenant_id, event_uuid);

create unique index if not exists idx_event_store_device_sequence
    on event_store (tenant_id, device_id, device_sequence);

insert into tenant (id, code, name, created_at)
values ('tenant-atlas-bites', 'atlas-bites', 'Atlas Bites Group', current_timestamp);

insert into branch (id, tenant_id, name, code, timezone, created_at)
values
    ('branch-oujda', 'tenant-atlas-bites', 'Oujda Flagship', 'OUJDA', 'Africa/Casablanca', current_timestamp),
    ('branch-rabat', 'tenant-atlas-bites', 'Rabat Express', 'RABAT', 'Africa/Casablanca', current_timestamp);
